kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Values.nameSpace.name }}
subjects:
- kind: ServiceAccount
  name:  {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.nameSpace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.name }}